
apiVersion: cert-manager.io/v1  # Version de l'API cert-manager utilisée
kind: ClusterIssuer  # Type de ressource Kubernetes : ClusterIssuer
metadata:
  name: production-cluster-issuer  # Nom du ClusterIssuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory  # URL du serveur ACME (Let's Encrypt)
    privateKeySecretRef:
      name: production-cluster-issuer  # Nom du secret Kubernetes qui stockera la clé privée
    solvers:
      - selector: {}  # Sélecteur pour spécifier les cibles pour lesquelles ce solveur s'applique
        http01:  # Méthode de validation HTTP-01 utilisée pour la vérification de domaine
          ingress:  # Configuration de la méthode de validation HTTP-01 via Ingress
            class: istio  # Classe de l'Ingress utilisée pour la validation HTTP-01 (dans ce cas, Istio)
